// generator/template/react.antd/src/views/Login/Login.js
import { useState } from 'react';
import { useHistory, useLocation } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import Cookies from 'js-cookie';
import './Login.css';
const idsProxy = '/ids';
function LoginPage() {
  let history = useHistory();
  let location = useLocation();
  const [loading, setLoading] = useState(false);
  const [verification, setVerification] = useState(`${idsProxy}/verification`);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [verifyCode, setVerifyCode] = useState('');

  let auth = useAuth();

  let { from } = location.state || { from: { pathname: '/' } };
  let login = () => {
    setLoading(true);
    let form = new FormData();
    form.append('username', username);
    form.append('password', password);
    form.append('verifyCode', verifyCode);
    fetch(`${idsProxy}/login`, {
      method: 'POST',
      body: form,
      credentials: 'include',
    })
      .then((response) => {
        return response.json();
      })
      .then((res) => {
        if (res && res.code === 200) {
          const { username, access_token } = res.data;
          auth.setState({
            account: username,
            token: access_token,
          });
          Cookies.set('token', access_token);
          Cookies.set('account', username);
          setLoading(false);
          history.replace(from);
        } else {
          setVerification(`${idsProxy}/verification?t=${new Date().getTime()}`);
        }
      });
  };

  return (
    <div className="login-page">
      <p>You must log in to view the page at: :{from.pathname}</p>

      <div>
        用户名：
        <input
          type="text"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        />
      </div>
      <div>
        密码：
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
      </div>
      <div>
        验证码：
        <input
          type="text"
          value={verifyCode}
          onChange={(e) => setVerifyCode(e.target.value)}
        />
        <img
          src={verification}
          alt=""
          onClick={() =>
            setVerification(
              `${idsProxy}/verification?t=${new Date().getTime()}`
            )
          }
        />
      </div>
      <button onClick={login}>{loading ? 'Logging in...' : 'Log in'}</button>
    </div>
  );
}

export default LoginPage;

// generator/template/micro.fe.vue.iview/src/views/Base/Login.vue
<template>
  <div class="login-page">
    <div class="login-page-wrapper">
      <p>You must log in to view the page at: :{{ redirect }}</p>

      <div class="login-form-item">
        用户名：<input type="text" v-model="formData.username" />
      </div>
      <div class="login-form-item">
        密 码：<input type="password" v-model="formData.password" />
      </div>
      <div class="login-form-item login-form-item-verify">
        验证码：<input type="text" v-model="formData.verifyCode" />
        <img :src="verification" alt="" @click="updateImg" />
      </div>
      <button class="login-form-submit" @click="login">
        {{ loading ? 'Logging in...' : 'Log in' }}
      </button>
    </div>
  </div>
</template>

<script>
const IDS_PROXY = process.env.VUE_APP_PROXY_IN_DEV_IDS || '';
export default {
  name: 'LoginPage',
  data() {
    return {
      loading: false,
      verification: `${IDS_PROXY}/verification`,
      formData: {
        username: '',
        password: '',
        verifyCode: '',
      },
    };
  },

  computed: {
    redirect() {
      return this.$route.query.redirect || '/';
    },
  },
  methods: {
    updateImg() {
      this.verification = `${IDS_PROXY}/verification?t=${new Date().getTime()}`;
    },
    login() {
      this.loading = true;
      const { username, password, verifyCode } = this.formData;
      let form = new FormData();
      form.append('username', username);
      form.append('password', password);
      form.append('verifyCode', verifyCode);
      fetch(`${IDS_PROXY}/login`, {
        method: 'POST',
        body: form,
        credentials: 'include',
      })
        .then((response) => {
          return response.json();
        })
        .then((res) => {
          if (res && res.code === 200) {
            const { username, access_token } = res.data;

            this.$Cookie.set('token', access_token);
            this.$Cookie.set('account', username);
            this.loading = false;
            this.$router.push(this.redirect);
          } else {
            this.loading = false;
            this.updateImg();
          }
        });
    },
  },
};
</script>
<style lang="less" scoped>
.login-page {
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.login-form-item {
  padding-top: 10px;
  padding-bottom: 10px;
}
.login-form-item input {
  width: 230px;
  height: 24px;
}
.login-form-item-verify {
  display: flex;
}
.login-form-item-verify input {
  width: 170px;
}
.login-form-item-verify img {
  width: 60px;
}
.login-form-submit {
  background-color: #1890ff;
  height: 32px;
  width: 100%;
  margin-top: 20px;
  color: #fff;
  cursor: pointer;
  border: none;
  border-radius: 4px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  -ms-border-radius: 4px;
  -o-border-radius: 4px;
}
</style>
